// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CosmosManagementApi.Models
{
    public partial class Budgets
    {
        public Budgets()
        {
            Expenses = new HashSet<Expenses>();
        }

        /// <summary>
        /// Budget Primary Key
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Budget Name
        /// </summary>
        public string BudgetName { get; set; }
        /// <summary>
        /// Budget Name Description
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// reserved amount
        /// </summary>
        public int? Amount { get; set; }
        /// <summary>
        /// Available balance amount
        /// </summary>
        public int? AbAmount { get; set; }
        /// <summary>
        /// Currency type
        /// </summary>
        public string Currency { get; set; }
        /// <summary>
        /// Reference key to project
        /// </summary>
        public int? ProjectId { get; set; }
        /// <summary>
        /// Remark of correlate budgets
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 1forDeleted
        /// </summary>
        public int? IsDeleted { get; set; }
        /// <summary>
        /// WhenDeleted
        /// </summary>
        public DateTime? DeletedTime { get; set; }

        public virtual Projects Project { get; set; }
        public virtual ICollection<Expenses> Expenses { get; set; }
    }
}