// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CosmosManagementApi.Models
{
    public partial class Expenses
    {
        /// <summary>
        /// Primary key for Expenses
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Expense name
        /// </summary>
        public string ExpenseName { get; set; }
        /// <summary>
        /// Description
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// Vendor name
        /// </summary>
        public string VendorName { get; set; }
        /// <summary>
        /// Proposal reference number
        /// </summary>
        public string ProposalNo { get; set; }
        /// <summary>
        /// PR service contract number
        /// </summary>
        public string PrNo { get; set; }
        /// <summary>
        /// Service period
        /// </summary>
        public string Period { get; set; }
        /// <summary>
        /// Forecast date
        /// </summary>
        public DateTime? Forecast { get; set; }
        /// <summary>
        /// MOP amount
        /// </summary>
        public int? Amount { get; set; }
        /// <summary>
        /// Actual Paid Amount
        /// </summary>
        public int? ApAmount { get; set; }
        /// <summary>
        /// Budget Reserved Amount
        /// </summary>
        public int? BrAmount { get; set; }
        /// <summary>
        /// Reserved but not paid amount
        /// </summary>
        public int? RpAmount { get; set; }
        /// <summary>
        /// Reference key budget
        /// </summary>
        public int? BudgetId { get; set; }
        /// <summary>
        /// 1fordeleted
        /// </summary>
        public int? IsDeleted { get; set; }
        /// <summary>
        /// WhenDeleted
        /// </summary>
        public DateTime? DeletedTime { get; set; }

        public virtual Budgets Budget { get; set; }
    }
}