// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CosmosManagementApi.Models
{
    public partial class Projects
    {
        public Projects()
        {
            Budgets = new HashSet<Budgets>();
            Schedules = new HashSet<Schedules>();
        }

        /// <summary>
        /// Primary key for Project Table
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Project name
        /// </summary>
        public string ProjectName { get; set; }
        /// <summary>
        /// Project English Name
        /// </summary>
        public string ProjectNameEn { get; set; }
        /// <summary>
        /// Project Investor Name
        /// </summary>
        public string ProjectInvestorName { get; set; }
        /// <summary>
        /// PI Faculty
        /// </summary>
        public string ProjectInvestorFaculty { get; set; }
        /// <summary>
        /// Scope
        /// </summary>
        public string ProjectScope { get; set; }
        /// <summary>
        /// Engagement Number
        /// </summary>
        public string ProjectENumber { get; set; }
        /// <summary>
        /// Engagement approved date
        /// </summary>
        public DateTime? ProjectEApprovedDate { get; set; }
        /// <summary>
        /// Project start date
        /// </summary>
        public DateTime? StartDate { get; set; }
        /// <summary>
        /// Project end date
        /// </summary>
        public DateTime? EndDate { get; set; }
        /// <summary>
        /// Project total income amount
        /// </summary>
        public int? TotalIncome { get; set; }
        /// <summary>
        /// Currency type
        /// </summary>
        public string Curency { get; set; }
        /// <summary>
        /// Commissioned_unit
        /// </summary>
        public string CommissionedUnit { get; set; }
        /// <summary>
        /// Contacter name
        /// </summary>
        public string ContactName { get; set; }
        /// <summary>
        /// Contacter phone number
        /// </summary>
        public string ContactPhone { get; set; }
        /// <summary>
        /// Contacter email
        /// </summary>
        public string ContactEmail { get; set; }
        /// <summary>
        /// ManagementFee percentage
        /// </summary>
        public int? ManagementPer { get; set; }
        /// <summary>
        /// ManagementFee
        /// </summary>
        public decimal? ManagementFee { get; set; }
        /// <summary>
        /// 1FORDeleted
        /// </summary>
        public int? IsDeleted { get; set; }
        /// <summary>
        /// WhenDeleted
        /// </summary>
        public DateTime? DeletedTime { get; set; }
        /// <summary>
        /// Project Number
        /// </summary>
        public string ProjectNumber { get; set; }
        /// <summary>
        /// Remark for Project
        /// </summary>
        public string Remark { get; set; }

        public virtual ICollection<Budgets> Budgets { get; set; }
        public virtual ICollection<Schedules> Schedules { get; set; }
    }
}