// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CosmosManagementApi.Models
{
    public partial class Schedules
    {
        /// <summary>
        /// Primary key for schedules
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Expected received date
        /// </summary>
        public DateTime? ExpectedDate { get; set; }
        public string Deliverables { get; set; }
        /// <summary>
        /// Received Amount
        /// </summary>
        public int? Amount { get; set; }
        /// <summary>
        /// ReferenceKet to Project
        /// </summary>
        public int? ProjectId { get; set; }

        public virtual Projects Project { get; set; }
    }
}